kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2
  annotations: 
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"
  zones: us-west-2a, us-west-2b, us-west-2c
reclaimPolicy: Delete
mountOptions:
  - debug 
